<a href="https://colab.research.google.com/github/Sakshijiwtode/practical-1/blob/main/Deep_learning_collab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Deep learning : Deep learning is a subset of machine learning, which is therefore a subset of artificial intelligence (AI). It is used to train itself to perform tasks, like speech and image recognition, by exposing multilayered neural networks to vast amounts of data.

Bias:A machine learning model analyzes data, looks for patterns and makes predictions. During training, the model learns these patterns in the dataset and applies them to the test data to make predictions. While making predictions, there is a difference between the predicted values of the model and the actual values and this difference is called bias. The bias is due to the assumptions of the model, which makes the objective function easy to learn. There are two types of bias: Low bias and high bias

In [4]:
import torch
import torch.nn as nn

# Define a simple MLP model with biases
class MLP(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(MLP, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)  # Linear layer with bias
        self.relu = nn.ReLU()  # ReLU activation
        self.fc2 = nn.Linear(hidden_size, num_classes)  # Another linear layer with bias

    def forward(self, x):
        out = self.fc1(x)  # Apply first linear layer
        out = self.relu(out)  # Apply ReLU activation
        out = self.fc2(out)  # Apply second linear layer
        return out

# Example usage
input_size = 784  # Example input size (e.g., 28x28 images flattened)
hidden_size = 500  # Number of neurons in the hidden layer
num_classes = 10  # Number of output classes

model = MLP(input_size, hidden_size, num_classes)

# Access the weights and biases of the first linear layer
fc1_weights = model.fc1.weight
fc1_biases = model.fc1.bias

print(f"First layer weights: {fc1_weights}")
print(f"First layer biases: {fc1_biases}")

# Access the weights and biases of the second linear layer
fc2_weights = model.fc2.weight
fc2_biases = model.fc2.bias

print(f"Second layer weights: {fc2_weights}")
print(f"Second layer biases: {fc2_biases}")


First layer weights: Parameter containing:
tensor([[ 0.0146, -0.0045,  0.0286,  ...,  0.0208,  0.0057,  0.0095],
        [-0.0007,  0.0245, -0.0049,  ..., -0.0060,  0.0126, -0.0333],
        [ 0.0334,  0.0163,  0.0086,  ..., -0.0095,  0.0058, -0.0048],
        ...,
        [-0.0309, -0.0293,  0.0270,  ..., -0.0110, -0.0170, -0.0176],
        [ 0.0236, -0.0283,  0.0097,  ...,  0.0200,  0.0102,  0.0001],
        [ 0.0072,  0.0083,  0.0065,  ...,  0.0214,  0.0022, -0.0225]],
       requires_grad=True)
First layer biases: Parameter containing:
tensor([-0.0152,  0.0061,  0.0195,  0.0007,  0.0298,  0.0196, -0.0239, -0.0039,
         0.0201, -0.0028, -0.0115,  0.0179,  0.0043,  0.0156, -0.0337, -0.0344,
        -0.0274,  0.0209,  0.0002, -0.0178, -0.0155,  0.0179,  0.0304, -0.0159,
         0.0176,  0.0169, -0.0249,  0.0151, -0.0271, -0.0139,  0.0194, -0.0104,
         0.0249, -0.0079,  0.0150,  0.0277,  0.0300, -0.0157,  0.0291,  0.0122,
        -0.0009, -0.0021, -0.0255,  0.0227, -0.0194, -

Variance is a variance of data points that are spread. It quantifies how much the values in a data set differ from the average of the data set variance is simply refered to the variation in model predictions.
There are two types High variance and Low variance
High variance gives the scattered graph as there is more gap in prediction value ahe actual value
Low variance give saturated graph as there is less gap in between predicted value and actual value.

Sample variance example

In [5]:
import torch

# Create a sample tensor
tensor = torch.tensor([[1.0, 2.0, 3.0],
                       [4.0, 5.0, 6.0],
                       [7.0, 8.0, 9.0]])

# Compute the variance of the entire tensor
var_all = torch.var(tensor)

# Compute the variance along the rows (dim=0)
var_rows = torch.var(tensor, dim=0)

# Compute the variance along the columns (dim=1)
var_cols = torch.var(tensor, dim=1)

print(f"Variance of the entire tensor: {var_all}")
print(f"Variance along the rows: {var_rows}")
print(f"Variance along the columns: {var_cols}")


Variance of the entire tensor: 7.5
Variance along the rows: tensor([9., 9., 9.])
Variance along the columns: tensor([1., 1., 1.])


 MLP stands for Multilayer Perceptron it is a type of artificial neural network commonly used for supervised learning for ex classification and regression. It consists of 3 layers -Input layer,Hidden layer and output layer.
Input.layer:It contains the neurons that receive the input features of the data. The number of neurons inthis layer is equal to the number of features in the dataset.
Hidden layer:It is made up of neurons that perform intermediate computations and feature extraction. It can Have one or more hidden layers, each with a configurable number of neurons. The number of hidden layers and neurons is a hyperparameter that can be tuned.
Output layer: It is responsible for final prediction and classification.The number of neurons in the output layer depends on the nature of the task


In [3]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define the MLP model
class MLP(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(MLP, self).__init__()
        # Define layers
        self.fc1 = nn.Linear(input_size, hidden_size)  # Input layer to hidden layer
        self.relu = nn.ReLU()                         # ReLU activation function
        self.fc2 = nn.Linear(hidden_size, num_classes) # Hidden layer to output layer

    def forward(self, x):
        out = self.fc1(x)  # Forward pass through the first layer
        out = self.relu(out)  # Apply ReLU activation
        out = self.fc2(out)  # Forward pass through the second layer
        return out

# Define the parameters
input_size = 784  # Example input size (e.g., 28x28 images flattened)
hidden_size = 500 # Number of neurons in the hidden layer
num_classes = 10  # Number of output classes (e.g., for digit classification 0-9)
num_epochs = 5    # Number of epochs to train
batch_size = 100  # Batch size for training
learning_rate = 0.001 # Learning rate

# Load dataset (example using MNIST)
from torchvision import datasets, transforms

transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])
train_dataset = datasets.MNIST(root='./data', train=True, transform=transform, download=True)
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)

# Initialize the model, loss function, and optimizer
model = MLP(input_size, hidden_size, num_classes)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Training loop
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):
        # Flatten the images
        images = images.reshape(-1, 28*28)

        # Forward pass
        outputs = model(images)
        loss = criterion(outputs, labels)

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if (i+1) % 100 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}], Step [{i+1}/{len(train_loader)}], Loss: {loss.item():.4f}')

print("Training complete.")


Epoch [1/5], Step [100/600], Loss: 0.3951
Epoch [1/5], Step [200/600], Loss: 0.3200
Epoch [1/5], Step [300/600], Loss: 0.2200
Epoch [1/5], Step [400/600], Loss: 0.2124
Epoch [1/5], Step [500/600], Loss: 0.2034
Epoch [1/5], Step [600/600], Loss: 0.0948
Epoch [2/5], Step [100/600], Loss: 0.2644
Epoch [2/5], Step [200/600], Loss: 0.1622
Epoch [2/5], Step [300/600], Loss: 0.1933
Epoch [2/5], Step [400/600], Loss: 0.2025
Epoch [2/5], Step [500/600], Loss: 0.0437
Epoch [2/5], Step [600/600], Loss: 0.1799
Epoch [3/5], Step [100/600], Loss: 0.0683
Epoch [3/5], Step [200/600], Loss: 0.0941
Epoch [3/5], Step [300/600], Loss: 0.0534
Epoch [3/5], Step [400/600], Loss: 0.0473
Epoch [3/5], Step [500/600], Loss: 0.1865
Epoch [3/5], Step [600/600], Loss: 0.1185
Epoch [4/5], Step [100/600], Loss: 0.0438
Epoch [4/5], Step [200/600], Loss: 0.0692
Epoch [4/5], Step [300/600], Loss: 0.0739
Epoch [4/5], Step [400/600], Loss: 0.1828
Epoch [4/5], Step [500/600], Loss: 0.1764
Epoch [4/5], Step [600/600], Loss:

Deep neural network : A deep neural network (DNN) is an artificial neural network with many hidden layers between the input and output layers. These additional layers allow the network to model complex patterns in data, making DNNs powerful for varietyof tasks such as image and speech recognition, natural language processing &  more.

In [6]:
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms

# Define the DNN model
class DNN(nn.Module):
    def __init__(self, input_size, hidden_sizes, num_classes):
        super(DNN, self).__init__()
        self.hidden_layers = nn.ModuleList()

        # Input layer to first hidden layer
        self.hidden_layers.append(nn.Linear(input_size, hidden_sizes[0]))
        self.hidden_layers.append(nn.ReLU())

        # Hidden layers
        for i in range(len(hidden_sizes) - 1):
            self.hidden_layers.append(nn.Linear(hidden_sizes[i], hidden_sizes[i + 1]))
            self.hidden_layers.append(nn.ReLU())

        # Output layer
        self.output_layer = nn.Linear(hidden_sizes[-1], num_classes)

    def forward(self, x):
        for layer in self.hidden_layers:
            x = layer(x)
        x = self.output_layer(x)
        return x

# Parameters
input_size = 784  # 28x28 images flattened
hidden_sizes = [512, 256, 128]  # Three hidden layers with respective sizes
num_classes = 10  # Number of output classes (digits 0-9)
num_epochs = 5  # Number of epochs
batch_size = 100  # Batch size
learning_rate = 0.001  # Learning rate

# MNIST dataset
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])
train_dataset = datasets.MNIST(root='./data', train=True, transform=transform, download=True)
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)

# Initialize model, loss function, and optimizer
model = DNN(input_size, hidden_sizes, num_classes)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Training loop
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):
        # Flatten the images
        images = images.view(-1, 28*28)

        # Forward pass
        outputs = model(images)
        loss = criterion(outputs, labels)

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if (i+1) % 100 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}], Step [{i+1}/{len(train_loader)}], Loss: {loss.item():.4f}')

print("Training complete.")


Epoch [1/5], Step [100/600], Loss: 0.5991
Epoch [1/5], Step [200/600], Loss: 0.2362
Epoch [1/5], Step [300/600], Loss: 0.2668
Epoch [1/5], Step [400/600], Loss: 0.2280
Epoch [1/5], Step [500/600], Loss: 0.2699
Epoch [1/5], Step [600/600], Loss: 0.1616
Epoch [2/5], Step [100/600], Loss: 0.1320
Epoch [2/5], Step [200/600], Loss: 0.2438
Epoch [2/5], Step [300/600], Loss: 0.1956
Epoch [2/5], Step [400/600], Loss: 0.1907
Epoch [2/5], Step [500/600], Loss: 0.1847
Epoch [2/5], Step [600/600], Loss: 0.2926
Epoch [3/5], Step [100/600], Loss: 0.2329
Epoch [3/5], Step [200/600], Loss: 0.1633
Epoch [3/5], Step [300/600], Loss: 0.0579
Epoch [3/5], Step [400/600], Loss: 0.1022
Epoch [3/5], Step [500/600], Loss: 0.1030
Epoch [3/5], Step [600/600], Loss: 0.1596
Epoch [4/5], Step [100/600], Loss: 0.0780
Epoch [4/5], Step [200/600], Loss: 0.1263
Epoch [4/5], Step [300/600], Loss: 0.1239
Epoch [4/5], Step [400/600], Loss: 0.0967
Epoch [4/5], Step [500/600], Loss: 0.0445
Epoch [4/5], Step [600/600], Loss:

Backpropagation is a fundamental algorithm used in training artificial neural networks, particularly in the context of supervised learning. It efficiently computes the gradient of the loss function with respect to each weight in the network, allowing for the optimization of the model through gradient descent.

In [7]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Generate a toy dataset
X, y = make_moons(n_samples=1000, noise=0.2, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Standardize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Convert to PyTorch tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.long)
y_test = torch.tensor(y_test, dtype=torch.long)

# Define a simple neural network
class SimpleNN(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out

# Model parameters
input_size = 2
hidden_size = 5
num_classes = 2
num_epochs = 100
learning_rate = 0.01

# Initialize the model, loss function, and optimizer
model = SimpleNN(input_size, hidden_size, num_classes)
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=learning_rate)

# Training loop
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(X_train)
    loss = criterion(outputs, y_train)

    # Backward pass and optimization
    optimizer.zero_grad()  # Clear gradients
    loss.backward()  # Compute gradients
    optimizer.step()  # Update weights

    if (epoch+1) % 10 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

print("Training complete.")

# Evaluate the model
model.eval()
with torch.no_grad():
    outputs = model(X_test)
    _, predicted = torch.max(outputs, 1)
    accuracy = (predicted == y_test).sum().item() / y_test.size(0)
    print(f'Accuracy: {accuracy*100:.2f}%')


Epoch [10/100], Loss: 0.6864
Epoch [20/100], Loss: 0.6811
Epoch [30/100], Loss: 0.6758
Epoch [40/100], Loss: 0.6706
Epoch [50/100], Loss: 0.6654
Epoch [60/100], Loss: 0.6603
Epoch [70/100], Loss: 0.6551
Epoch [80/100], Loss: 0.6498
Epoch [90/100], Loss: 0.6445
Epoch [100/100], Loss: 0.6392
Training complete.
Accuracy: 76.67%


ActivationThe activation function must decide whether a neuron should be activated or not by calculating a weighted sum of its inputs and adding a bias. This process allows the network to learn and perform more complex tasks by changing the input in a non-linear fashion. Essentially, activation functions help mode complex relationships in data, which is crucial for tasks like classification and regression.


Sigmoid
Range: 0 to 1
Use: Often used in the output layer for binary classification tasks. However, it can lead to issues like vanishing gradients during training.

In [8]:
import torch
import torch.nn as nn

# Input tensor
x = torch.tensor([[-1.0, 2.0, -3.0], [4.0, -5.0, 6.0]])

# Sigmoid activation function
sigmoid = nn.Sigmoid()
output = sigmoid(x)

print("Input:\n", x)
print("Output after Sigmoid:\n", output)


Input:
 tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])
Output after Sigmoid:
 tensor([[0.2689, 0.8808, 0.0474],
        [0.9820, 0.0067, 0.9975]])


ReLU (Rectified Linear Unit)
Range: 0 to ∞
Use: Widely used in hidden layers of deep networks due to its simplicity and effectiveness in mitigating the vanishing gradient problem

In [9]:
import torch
import torch.nn as nn

# Input tensor
x = torch.tensor([[-1.0, 2.0, -3.0], [4.0, -5.0, 6.0]])

# ReLU activation function
relu = nn.ReLU()
output = relu(x)

print("Input:\n", x)
print("Output after ReLU:\n", output)


Input:
 tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])
Output after ReLU:
 tensor([[0., 2., 0.],
        [4., 0., 6.]])


Tanh (Hyperbolic Tangent) Function:
Range: -1 to 1
Use: Generally preferred over the sigmoid function due to its zero-centered output, which helps in faster convergence during training.

In [10]:
import torch
import torch.nn as nn

# Input tensor
x = torch.tensor([[-1.0, 2.0, -3.0], [4.0, -5.0, 6.0]])

# Tanh activation function
tanh = nn.Tanh()
output = tanh(x)

print("Input:\n", x)
print("Output after Tanh:\n", output)


Input:
 tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])
Output after Tanh:
 tensor([[-0.7616,  0.9640, -0.9951],
        [ 0.9993, -0.9999,  1.0000]])


Leaky ReLU:
Range: −∞ to +∞
Use: Addresses the "dying ReLU" problem by allowing a small gradient when the unit is not active.

In [11]:
import torch
import torch.nn as nn

# Input tensor
x = torch.tensor([[-1.0, 2.0, -3.0], [4.0, -5.0, 6.0]])

# Leaky ReLU activation function
leaky_relu = nn.LeakyReLU(negative_slope=0.01)
output = leaky_relu(x)

print("Input:\n", x)
print("Output after Leaky ReLU:\n", output)


Input:
 tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])
Output after Leaky ReLU:
 tensor([[-0.0100,  2.0000, -0.0300],
        [ 4.0000, -0.0500,  6.0000]])


Softmax Function:
Range: 0 to 1 (sums to 1 across multiple outputs)
Use: Commonly used in the output layer for multi-class classification tasks.

In [12]:
import torch
import torch.nn as nn

# Input tensor
x = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# Softmax activation function
softmax = nn.Softmax(dim=1)
output = softmax(x)

print("Input:\n", x)
print("Output after Softmax:\n", output)


Input:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
Output after Softmax:
 tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])


Regularization: Regularization is a set of techniques that prevent machine learning models from overfitting by adding additional information or constraints to the model. Overfitting occurs when the model learns not only the underlying patterns in the training data but also noise and outliers, resulting in poor generalization from unseen data. Regularization helps improve the generalizability of the model by penalizing complex models. Here are some of the more common legalization techniques.
L1 Regularization (Lasso),L2 Regularization (Ridge),Elastic Net,Dropout and Weight Decay.

Regularization techniques are used in machine learning to prevent overfitting by adding a penalty to the loss function. Two common regularization techniques are L2 regularization (also known as weight decay) and Dropout. Below is an example of how to implement these techniques in PyTorch.L2 regularization and Dropout to a simple neural network model.

In [13]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Generate a toy dataset
X, y = make_moons(n_samples=1000, noise=0.2, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Standardize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Convert to PyTorch tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.long)
y_test = torch.tensor(y_test, dtype=torch.long)

# Define a simple neural network with Dropout
class SimpleNN(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(p=0.5)  # Dropout with 50% probability
        self.fc2 = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.dropout(out)
        out = self.fc2(out)
        return out

# Model parameters
input_size = 2
hidden_size = 5
num_classes = 2
num_epochs = 100
learning_rate = 0.01
weight_decay = 0.001  # L2 regularization parameter

# Initialize the model, loss function, and optimizer with weight decay
model = SimpleNN(input_size, hidden_size, num_classes)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate, weight_decay=weight_decay)

# Training loop
for epoch in range(num_epochs):
    model.train()  # Set the model to training mode
    # Forward pass
    outputs = model(X_train)
    loss = criterion(outputs, y_train)

    # Backward pass and optimization
    optimizer.zero_grad()  # Clear gradients
    loss.backward()  # Compute gradients
    optimizer.step()  # Update weights

    if (epoch+1) % 10 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

print("Training complete.")

# Evaluate the model
model.eval()  # Set the model to evaluation mode
with torch.no_grad():
    outputs = model(X_test)
    _, predicted = torch.max(outputs, 1)
    accuracy = (predicted == y_test).sum().item() / y_test.size(0)
    print(f'Accuracy: {accuracy*100:.2f}%')


Epoch [10/100], Loss: 0.8680
Epoch [20/100], Loss: 0.6897
Epoch [30/100], Loss: 0.5606
Epoch [40/100], Loss: 0.4819
Epoch [50/100], Loss: 0.4539
Epoch [60/100], Loss: 0.4536
Epoch [70/100], Loss: 0.4498
Epoch [80/100], Loss: 0.4077
Epoch [90/100], Loss: 0.4064
Epoch [100/100], Loss: 0.4322
Training complete.
Accuracy: 89.00%


Convolutional Neural Networks (CNNs) are a specialized deep learning architecture used primarily for computer vision tasks such as image classification and object detection. They are designed to automatically and adaptively learn spatial hierarchies of features from input images.

In [15]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms

# Define the CNN model
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        # Convolutional layer 1
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=16, kernel_size=5, stride=1, padding=2)
        self.relu1 = nn.ReLU()
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2, padding=0)

        # Convolutional layer 2
        self.conv2 = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=5, stride=1, padding=2)
        self.relu2 = nn.ReLU()

        # Fully connected layer 1
        self.fc1 = nn.Linear(32 * 7 * 7, 100)
        self.relu3 = nn.ReLU()

        # Fully connected layer 2 (output layer)
        self.fc2 = nn.Linear(100, 10)

    def forward(self, x):
        # Apply first convolutional layer, ReLU and max pooling
        x = self.pool(self.relu1(self.conv1(x)))

        # Apply second convolutional layer, ReLU and max pooling
        x = self.pool(self.relu2(self.conv2(x)))

        # Flatten the output from the conv layers
        x = x.view(-1, 32 * 7 * 7)

        # Apply first fully connected layer and ReLU
        x = self.relu3(self.fc1(x))

        # Apply second fully connected layer (output layer)
        x = self.fc2(x)

        return x

# Transformations for the dataset
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

# Load the dataset
train_dataset = torchvision.datasets.MNIST(root='./data', train=True, transform=transform, download=True)
test_dataset = torchvision.datasets.MNIST(root='./data', train=False, transform=transform)

train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size=100, shuffle=True)
test_loader = torch.utils.data.DataLoader(dataset=test_dataset, batch_size=100, shuffle=False)

# Model, loss function, optimizer
model = CNN()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training the model
num_epochs = 5
for epoch in range(num_epochs):
    model.train()
    for images, labels in train_loader:
        # Forward pass
        outputs = model(images)
        loss = criterion(outputs, labels)

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

# Testing the model
model.eval()
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in test_loader:
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    print(f'Accuracy of the model on the 10000 test images: {100 * correct / total:.2f}%')


Epoch [1/5], Loss: 0.0574
Epoch [2/5], Loss: 0.0580
Epoch [3/5], Loss: 0.0210
Epoch [4/5], Loss: 0.0236
Epoch [5/5], Loss: 0.0017
Accuracy of the model on the 10000 test images: 99.07%


RNNs: Recurrent Neural Networks (RNNs) are a class of artificial neural networks designed to process sequential data, making them particularly effective for tasks that involve time series, natural language, and other ordered data. Unlike traditional feedforward neural networks, RNNs have connections that loop back on themselves, allowing them to maintain a form of memory about previous inputs.

In [16]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

# Prepare data
text = "hello pytorch, this is an example of rnn implementation."
chars = sorted(list(set(text)))
char_to_ix = {ch: i for i, ch in enumerate(chars)}
ix_to_char = {i: ch for i, ch in enumerate(chars)}
data_size, vocab_size = len(text), len(chars)

# Hyperparameters
input_size = vocab_size
hidden_size = 128
output_size = vocab_size
num_layers = 1
learning_rate = 0.01
num_epochs = 500

# Prepare inputs and targets
seq_length = 5
X_data = []
y_data = []

for i in range(0, data_size - seq_length):
    X_seq = text[i:i + seq_length]
    y_seq = text[i + 1:i + seq_length + 1]
    X_data.append([char_to_ix[ch] for ch in X_seq])
    y_data.append([char_to_ix[ch] for ch in y_seq])

X_data = torch.tensor(X_data, dtype=torch.long)
y_data = torch.tensor(y_data, dtype=torch.long)

# Define the RNN model
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size, num_layers):
        super(RNN, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.embed = nn.Embedding(input_size, hidden_size)
        self.rnn = nn.RNN(hidden_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)
        x = self.embed(x)
        out, _ = self.rnn(x, h0)
        out = self.fc(out)
        return out

# Initialize the model, loss function, and optimizer
model = RNN(input_size, hidden_size, output_size, num_layers)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Training the model
for epoch in range(num_epochs):
    model.train()
    outputs = model(X_data)
    loss = criterion(outputs.view(-1, vocab_size), y_data.view(-1))

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1) % 50 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

# Testing the model
model.eval()
with torch.no_grad():
    # Start with the first character
    input_seq = text[:seq_length]
    input_seq_ix = [char_to_ix[ch] for ch in input_seq]
    input_seq_tensor = torch.tensor([input_seq_ix], dtype=torch.long)

    predicted_seq = input_seq

    for _ in range(100):
        output = model(input_seq_tensor)
        output = output[:, -1, :]
        _, predicted_ix = torch.max(output, 1)
        predicted_char = ix_to_char[predicted_ix.item()]
        predicted_seq += predicted_char

        input_seq_tensor = torch.tensor([[char_to_ix[ch] for ch in predicted_seq[-seq_length:]]], dtype=torch.long)

    print(f'Predicted sequence: {predicted_seq}')


Epoch [50/500], Loss: 0.2428
Epoch [100/500], Loss: 0.2421
Epoch [150/500], Loss: 0.2420
Epoch [200/500], Loss: 0.2420
Epoch [250/500], Loss: 0.2418
Epoch [300/500], Loss: 0.2418
Epoch [350/500], Loss: 0.2418
Epoch [400/500], Loss: 0.2418
Epoch [450/500], Loss: 0.2417
Epoch [500/500], Loss: 0.2418
Predicted sequence: hello pytorch, this is an example of rnn implementation.ementation.ementation.ementation.ementation.ement


Transformer: Transformer Architecture is a model that uses self-attention that transforms one whole sentence into a single sentence. This is a big shift from how older models work step by step, and it helps overcome the challenges seen in models like RNNs and LSTMs

In [17]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

# Sample data
src_vocab_size = 10
tgt_vocab_size = 10
src_seq_length = 6
tgt_seq_length = 6
batch_size = 2

src = torch.randint(0, src_vocab_size, (batch_size, src_seq_length))
tgt = torch.randint(0, tgt_vocab_size, (batch_size, tgt_seq_length))

# Define the Transformer model
class Transformer(nn.Module):
    def __init__(self, src_vocab_size, tgt_vocab_size, d_model, nhead, num_encoder_layers, num_decoder_layers, dim_feedforward, dropout):
        super(Transformer, self).__init__()
        self.src_embedding = nn.Embedding(src_vocab_size, d_model)
        self.tgt_embedding = nn.Embedding(tgt_vocab_size, d_model)
        self.pos_encoder = nn.Sequential(
            nn.Linear(d_model, d_model),
            nn.ReLU(),
            nn.Linear(d_model, d_model)
        )
        self.transformer = nn.Transformer(d_model, nhead, num_encoder_layers, num_decoder_layers, dim_feedforward, dropout)
        self.fc_out = nn.Linear(d_model, tgt_vocab_size)

    def forward(self, src, tgt):
        src = self.src_embedding(src) * torch.sqrt(torch.tensor(d_model, dtype=torch.float32))
        tgt = self.tgt_embedding(tgt) * torch.sqrt(torch.tensor(d_model, dtype=torch.float32))
        src = self.pos_encoder(src)
        tgt = self.pos_encoder(tgt)
        src = src.permute(1, 0, 2)
        tgt = tgt.permute(1, 0, 2)
        memory = self.transformer.encoder(src)
        out = self.transformer.decoder(tgt, memory)
        out = self.fc_out(out.permute(1, 0, 2))
        return out

# Hyperparameters
d_model = 512
nhead = 8
num_encoder_layers = 3
num_decoder_layers = 3
dim_feedforward = 2048
dropout = 0.1
learning_rate = 0.001
num_epochs = 20

# Initialize the model, loss function, and optimizer
model = Transformer(src_vocab_size, tgt_vocab_size, d_model, nhead, num_encoder_layers, num_decoder_layers, dim_feedforward, dropout)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Training the model
for epoch in range(num_epochs):
    model.train()
    optimizer.zero_grad()
    output = model(src, tgt[:, :-1])
    loss = criterion(output.reshape(-1, tgt_vocab_size), tgt[:, 1:].reshape(-1))
    loss.backward()
    optimizer.step()

    if (epoch+1) % 5 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

# Testing the model (just a forward pass for demonstration)
model.eval()
with torch.no_grad():
    output = model(src, tgt[:, :-1])
    print("Output shape:", output.shape)
    print("Output:", output)


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:306: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")


Epoch [5/20], Loss: 2.2506
Epoch [10/20], Loss: 1.7717
Epoch [15/20], Loss: 1.7431
Epoch [20/20], Loss: 1.7012
Output shape: torch.Size([2, 5, 10])
Output: tensor([[[-4.2054, -3.7651,  2.8994,  2.6815, -4.9354,  1.9238,  1.3583,
          -3.6667,  3.2336,  3.2356],
         [-4.2066, -3.7646,  2.8985,  2.6841, -4.9356,  1.9220,  1.3588,
          -3.6666,  3.2346,  3.2345],
         [-4.2066, -3.7646,  2.8985,  2.6841, -4.9356,  1.9220,  1.3588,
          -3.6666,  3.2346,  3.2345],
         [-4.2045, -3.7647,  2.8989,  2.6802, -4.9339,  1.9208,  1.3555,
          -3.6660,  3.2280,  3.2458],
         [-4.2006, -3.7674,  2.9110,  2.6681, -4.9379,  1.9433,  1.3614,
          -3.6669,  3.2213,  3.2283]],

        [[-4.1661, -3.7812,  2.8991,  2.4247, -4.9598,  2.1199,  1.4273,
          -3.6680,  3.2238,  3.1951],
         [-4.1682, -3.7815,  2.8983,  2.4292, -4.9599,  2.1163,  1.4277,
          -3.6687,  3.2237,  3.1949],
         [-4.1639, -3.7821,  2.9047,  2.4210, -4.9598,  2.1256,  